Disable the JIT on riscv64.
Build fails with:

src/pcre2_jit_compile.c:81:2: error: #error Unsupported architecture
 #error Unsupported architecture
  ^~~~~

This is analogous to the same change made for pcre
(commit a276af83c829ae0589a27d5efb8dc97ce7195f3d).